name: Nightly

on:
  push:
    branches:
      - staging
    paths-ignore:
      - '.devcontainer/**'
      - '.zed/**'
      - '.husky/**'
      - 'docs/**'
      - 'release/**'

jobs:
  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    name: 'Build and push image 🔨🚀'
    runs-on: ubuntu-latest
    # needs: sonarcloud
    environment:
      name: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_NODE_ENV: production
          envkey_CONTACT_MAIL: ${{ secrets.CONTACT_MAIL }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
          envkey_NEXT_PUBLIC_FRONTEND_URL: ${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
          envkey_NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
          envkey_NEXT_PUBLIC_DISCORD_SERVER_URL: ${{ secrets.NEXT_PUBLIC_DISCORD_SERVER_URL }}
          envkey_SMTP_EMAIL: bde.isima.webmaster@gmail.com
          envkey_SMTP_USER: bde.isima.webmaster
          envkey_SMTP_HOST: ${{ secrets.SMTP_HOST }}
          envkey_SMTP_PORT: ${{ secrets.SMTP_PORT }}
          envkey_SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/bde-isima/bde.isima.fr/staging:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name:  Connecting via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        port: 22
        script_stop: true # stop script on first error
        script: |
          docker pull -q ghcr.io/bde-isima/bde.isima.fr/staging:latest
          if [ "$(docker ps -aq -f name=bde_app_dev)" ]; then
          docker stop bde_app_dev && docker rm bde_app_dev
            fi
          docker run -d --name bde_app_dev --network ubuntu_bde_isima_net ghcr.io/bde-isima/bde.isima.fr/staging:latest 
          docker image prune -f
          docker exec bde_nginx nginx -s reload
      
